name: Verilator Test

on:
  push:
  pull_request:

jobs:
  verilator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Verilator
        run: |
          sudo apt update
          sudo apt install -y verilator

      - name: Install icarus
        run: |
          sudo apt install -y iverilog

      - name: Run Tests
        run: |
          make test TEST=spi_peripheral_tb
